python aestrella.py ./ASTAR-tests mapa3 contenedores4 heuristica1
python aestrella.py ./ASTAR-tests mapa3 contenedores5 heuristica1
python aestrella.py ./ASTAR-tests mapa3 contenedores3 heuristica1
python aestrella.py ./ASTAR-tests mapa3 contenedores4 heuristica2
python aestrella.py ./ASTAR-tests mapa3 contenedores5 heuristica2
python aestrella.py ./ASTAR-tests mapa3 contenedores3 heuristica2
python aestrella.py ./ASTAR-tests mapa6 contenedores4 heuristica1
python aestrella.py ./ASTAR-tests mapa7 contenedores3 heuristica1
python aestrella.py ./ASTAR-tests mapa7 contenedores3 heuristica2
python aestrella.py ./ASTAR-tests mapa5 contenedores3 heuristica1
