./ASTARStowage.sh ./ASTAR-tests mapa3 contenedores4 heuristica1
./ASTARStowage.sh ./ASTAR-tests mapa3 contenedores5 heuristica1
./ASTARStowage.sh ./ASTAR-tests mapa3 contenedores3 heuristica1
./ASTARStowage.sh ./ASTAR-tests mapa3 contenedores4 heuristica2
./ASTARStowage.sh ./ASTAR-tests mapa3 contenedores5 heuristica2
./ASTARStowage.sh ./ASTAR-tests mapa3 contenedores3 heuristica2
./ASTARStowage.sh ./ASTAR-tests mapa6 contenedores4 heuristica1
./ASTARStowage.sh ./ASTAR-tests mapa7 contenedores3 heuristica1
./ASTARStowage.sh ./ASTAR-tests mapa7 contenedores3 heuristica2
./ASTARStowage.sh ./ASTAR-tests mapa5 contenedores3 heuristica2
